theme = "hugo-now-ui"
baseurl = "/"
languageCode = "en-us"
title = "R-Ladies Global"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "public"
disableKinds = ["taxonomy", "taxonomyTerm", "category", "sitemap", "RSS", "404", "robotsTXT", "home", "section"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About us"
    url = "#"
    identifier = "dropdown"
    pre = "<i class='now-ui-icons ui-2_favourite-28'></i>"
    weight = 1
[[menu.main]]
    name = "Mission"
    url = "/mission/"
    weight = 1
    parent = "dropdown"
[[menu.main]]
    name = "Get involved"
    url = "/involved/"
    weight = 2
    parent = "dropdown"
[[menu.main]]
    name = "Meet the global team"
    url = "/global-team/"
    weight = 3
    parent = "dropdown"
[[menu.main]]
    name = "R-Ladies Directory"
    url = "/directory/"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 2
[[menu.main]]
    name = "Events"
    url = "/events/"
    pre = "<i class='now-ui-icons ui-1_calendar-60'></i>"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "https://blog.rladies.org/"
    pre = "<i class='now-ui-icons ui-1_send'></i>"
    weight = 4
[[menu.main]]
    name = "Contact us"
    url = "/contact/"
    pre = "<i class='now-ui-icons ui-2_chat-round'></i>"
    weight = 4
[[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    pre = "<i class='now-ui-icons ui-2_like'></i>"
    weight = 5
    
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fab fa-2x fa-twitter'></i>"
    url = "https://twitter.com/rladiesglobal"
    weight = 1
[[menu.footer]]
    identifier = "instagram"
    pre = "<i class='fab fa-2x fa-instagram'></i>"
    url = "https://www.instagram.com/rladiesglobal"
    weight = 2
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fab fa-2x fa-github'></i>"
    url = "https://github.com/rladies"
    weight = 3
[[menu.footer]]
    identifier = "email"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
    url = "mailto:info@rladies.org"
    weight = 4
[[menu.footer]]
    identifier = "slack"
    pre = "<i class='fab fa-2x fa-slack'></i>"
    url = "https://rladies-community-slack.herokuapp.com/"
    weight = 5


[params]
    name = "R-Ladies Global"
    year = 2018
    background = "/img/user2017.jpg"
    tint = "purple"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "World-Wide Organization to promote gender diversity in the R Community"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


    

